// scripts/gen_match_seed.mjs
// Generates seed inserts for matches + match_players from the mock MATCHES array.
// Run: node scripts/gen_match_seed.mjs > /tmp/match_inserts.sql

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataPath = resolve(__dirname, '../web/src/data/data.ts');
const src = readFileSync(dataPath, 'utf8');

// Extract MATCHES literal by simple regex (deterministic format).
const start = src.indexOf('export const MATCHES: Match[] = [');
const end   = src.indexOf('];', start);
const body  = src.slice(start + 'export const MATCHES: Match[] = ['.length, end);

// Parse each line: { id: N, game: "x", date: "...", players: [...], winner: "x" }
const MATCHES = [];
for (const raw of body.split('\n')) {
  const m = raw.match(/\{\s*id:\s*(\d+),\s*game:\s*"([^"]+)",\s*date:\s*"([^"]+)",\s*players:\s*\[([^\]]+)\],\s*winner:\s*"([^"]+)"/);
  if (!m) continue;
  const players = m[4].split(',').map(s => s.trim().replace(/"/g, ''));
  MATCHES.push({ id: +m[1], game: m[2], date: m[3], players, winner: m[5] });
}

const PLAYER_UUID = {
  mara:  '22222222-0000-0000-0000-000000000001',
  tomas: '22222222-0000-0000-0000-000000000002',
  lena:  '22222222-0000-0000-0000-000000000003',
  wren:  '22222222-0000-0000-0000-000000000004',
  jules: '22222222-0000-0000-0000-000000000005',
  otto:  '22222222-0000-0000-0000-000000000006',
  hana:  '22222222-0000-0000-0000-000000000007',
  felix: '22222222-0000-0000-0000-000000000008',
};
const GROUP = '11111111-1111-1111-1111-111111111111';

const matchUuid = id => `33333333-0000-0000-0000-${String(id).padStart(12,'0')}`;

const lines = [];
lines.push('-- generated by scripts/gen_match_seed.mjs');
for (const m of MATCHES) {
  const mid = matchUuid(m.id);
  lines.push(
    `insert into public.matches (id, group_id, game_id, played_on, winner_member_id) values ` +
    `('${mid}','${GROUP}','${m.game}','${m.date}','${PLAYER_UUID[m.winner]}');`
  );
  for (const p of m.players) {
    lines.push(
      `insert into public.match_players (match_id, member_id) values ('${mid}','${PLAYER_UUID[p]}');`
    );
  }
}
console.log(lines.join('\n'));
console.error(`Generated ${MATCHES.length} matches`);
